### ISSUE TITLE
[Umbrella Issue] Code style and linting errors cleanup

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1176]
This issue will track cleanup duties related to code style and linting errors. Each will be described in different issues and implemented in corresponding PR. Feel free to suggest more changes that should be applied under this category as comments and they will be added to the list. Keep the discussion related to a specific topic in their corresponding issues.

- [x] ~Error string formatting: #1177~ **Merged**
- [x] ~Unused exported functions removal: #1178~ **Merged**
- [x] ~Unused parameters replacement by blank identifier: #1179~ **Merged**
- [x] Explicit errors handling: #1180
- [x] ~Package name as exported variable/type/function prefix removal: #1181~ **Merged**
- [x] ~Unification of receiver names: #1182~ **Merged**
- [x] ~Imports ordering: #1183~ **Merged**
- [x] Redundant type removal: #1188

/kind cleanup

**Comment by camilamacedo86** [comment]
HI @Adirio, 

Could you please provide what linter tool you are using and its report with the errors for each kind added here?

**Comment by Adirio** [comment]
My IDE has an integrated linter and I've started from there. Adding linter to the CI is not recommended as lint errors are just style recommendations, sometimes they may not be followed due to any other reason and if it gets added to the CI process it would get blocked.

**Comment by camilamacedo86** [comment]
> My IDE has an integrated linter and I've started from there
What linter are you using in your iDE?

>Adding linter to the CI is not recommended as lint errors are just style recommendations 
Linters are not just about style recommendations. See: https://github.com/golangci/awesome-go-linters

> sometimes they may not be followed due to any other reason and if it gets added to the CI process it would get blocked.

It has something that should not be merged and checked then, usually it should be done automatically by the CI in order to avoid it, otherwise, the same kind of issues/prs will still be required and the problem will be not solved. 

I common linter which is aggregator which means will check the style but not just it is : https://github.com/golangci/golangci-lint. Also, it do not get too long to be executed which usually is the problem to add linters in the CI and be called used by a command line. Also, since the project has the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/830 I'd recommend you use this one.

**Comment by Adirio** [comment]
Quoted from golang/lint:

> The suggestions made by golint are exactly that: suggestions. Golint is not perfect, and has both false positives and false negatives. Do not treat its output as a gold standard. We will not be adding pragmas or other knobs to suppress specific warnings, so do not expect or require code to be completely "lint-free". In short, this tool is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process. Golint makes suggestions for many of the mechanically checkable items listed in [Effective Go](https://golang.org/doc/effective_go.html) and the [CodeReviewComments wiki page](https://golang.org/wiki/CodeReviewComments).

**Comment by camilamacedo86** [comment]
HI @Adirio, 

In my above comment, I made more than one suggestion as follows. 

**Regards the PR's:**

IHMO if you would like to working on fixing linter issues to improve the quality of the code is required make clear what linter and its results as argumentation of the PR's in order to allow the reviewer check if it is solved or not for all repo and what is actually the motivation for them. Note that no make sense we have many PR's just to do the same as for example replace the capital letters to lower ones in the errors. 

**Regards add a specific linter in the CI**

I'd recommend you use  [golangci-lint](https://github.com/golangci/golangci-lint) because of:

- Ensure that the same issues will not be introduced after again
- Make clear what has been checked and what is expected
- It is a common linter to be used
- It is easy to be called since allows we check it by command line
- It is fast and will not make the PR's take to long to be checked.
- Also, because the project has already #830 to add it and fix the issues for the scaffold project which no maintainer make objections. 
- Also, **it has annotations to ignore linter specific lines of code if be required**. See https://github.com/golangci/golangci-lint#nolint

WDYT @DirectXMan12 and @droot. Could we adopt this one? Any objection about doing a PR with it in the CI for we are able to check its errors and the progress of this task which @Adirio goes is to solve all possible linter issues in the project?

**Comment by Adirio** [comment]
I'm not going to answer the "linter in CI" topic as I think that is a higher level decission that should be taken by the project mantainers who you already mentioned. This may actually be a good place to discuss it unless any other mean is proposed.

About the other comments:
- They are project-wide PRs. All of them. As it is a small-ish project, some of the PRs are pretty small, but I inspected the whole kubebuilder code. The only part that may be skiped by the linter is the generated files, I'll try to have a look at them but that will require mostly manual inspection as they are strings and scaffolded files outside of expected paths (v1 testdata for example).
- I'll try to improve the description but the titles contain most of the information that it is provided by the linter. Will try to look for a bit longer descriptions.

**Comment by Adirio** [comment]
@camilamacedo86 I added the exact message and description from the linter in the four Issues that have a PR (and in their corresponding PRs too). Will do the same when I tackle the remaining ones.

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

How can we reproduce the issue and check the messages in order to verify your PRs? How can any contributor work on in the tasks whiteout the linter info?  

from the above msg:
>  See also, that the README page has a badge for: https://goreportcard.com/report/sigs.k8s.io/kubebuilder. May you like to use it to illustrate the motivation for the PR's.

I hope that the above questions can clarifies the points.

**Comment by Adirio** [comment]
As you may see in the specific issues most of the modifications are related to CodeReviewComments or Effective Go. Most linters should hint this errors. In my case, Im using the linter hints from my IDE, which is not open source nor free so I can't suggest to download it.
Note: Bugs require reproducibility, but this are cleanup-oriented issues and PRs, that's why I don't think that exact steps need to be provided. Don't missunderstand me, if I could provide them I would, but as I'm using a IDE that isn't free.

**Comment by camilamacedo86** [comment]
Your IDE uses a specific linter. So, in order to clarify my suggestion would be you check what linter is and add in the comment. It would be enough.

**Comment by Adirio** [comment]
It is builtin in the IDE, it is not an external plugin. The code of the IDE is not open source. The only documentation provided is:
> ### Inspections & quick-fixes
> The IDE provides built-in inspections that check your code on the fly as you type it. When they find problematic code, they provide you with quick-fixes which you can apply simply by pressing Alt+Enter.

**Comment by camilamacedo86** [comment]
HI, could you please assign the issue to you in order to avoid other dev get it since you gave a PR already one for this one? Also, devs will usually filter for the unassigned ones to know what they can do to contribute with. 

PS.: To do it just add a new comment with `/assign @your user`
