### ISSUE TITLE
[Umbrella Issue] GolangCI lint

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1309]
GolangCI uses [several different linters](https://github.com/golangci/golangci-lint#supported-linters) concurrently to asses the code quality of this repository.

This issue lists which ones are implemented in this project:

- [ ] [bodyclose](https://github.com/timakin/bodyclose)
- [x] [deadcode](https://github.com/remyoudompheng/go-misc/tree/master/deadcode): #1205
- [ ] [depguard](https://github.com/OpenPeeDeeP/depguard)
- [ ] [dogsled](https://github.com/alexkohler/dogsled)
- [x] [dupl](https://github.com/mibk/dupl): #1205
- [x] [errcheck](https://github.com/kisielk/errcheck): #1205
- [ ] [funlen](https://github.com/ultraware/funlen)
- [ ] [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals)
- [ ] [gochecknoinits](https://github.com/leighmcculloch/gochecknoinits)
- [ ] [gocognit](https://github.com/uudashr/gocognit)
- [x] [goconst](https://github.com/jgautheron/goconst): #1294
- [ ] [gocritic](https://github.com/go-critic/go-critic)
- [x] [gocyclo](https://github.com/alecthomas/gocyclo): #1302
- [ ] [godox](https://github.com/matoous/godox)
- [x] [gofmt](https://golang.org/cmd/gofmt/): #1310
- [x] [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports): #1292
- [x] [golint](https://github.com/golang/lint): #1291
- [ ] [gomnd](https://github.com/tommy-muehle/go-mnd)
- [ ] [goprintffuncname](https://github.com/jirfag/go-printf-func-name)
- [x] [gosec](https://github.com/securego/gosec): #1304
- [x] [gosimple](https://github.com/dominikh/go-tools/tree/master/simple): #1312
- [x] [govet](https://golang.org/cmd/vet/): #1310
- [x] [ineffassign](https://github.com/gordonklaus/ineffassign): #1205
- [x] [interfacer](https://github.com/mvdan/interfacer): #1205
- [x] [lll](https://github.com/walle/lll): #1305
- [x] [maligned](https://github.com/mdempsky/maligned): #1293
- [x] [misspell](https://github.com/client9/misspell): #1205
- [x] [nakedret](https://github.com/alexkohler/nakedret): #1205
- [x] [prealloc](https://github.com/alexkohler/prealloc): #1335
- [ ] [rowserrcheck](https://github.com/jingyugao/rowserr)
- [x] [scopelint](https://github.com/kyoh86/scopelint): #1335
- [x] [staticcheck](https://staticcheck.io/): #1312
- [x] [structcheck](https://github.com/opennota/check): #1205
- [ ] [stylecheck](https://github.com/dominikh/go-tools/tree/master/stylecheck)
- [x] typecheck: #1335
- [x] [unconvert](https://github.com/mdempsky/unconvert); #1335
- [x] [unparam](https://github.com/mvdan/unparam): #1205
- [x] [unused](https://github.com/dominikh/go-tools/tree/master/unused): #1312
- [x] [varcheck](https://github.com/opennota/check): #1205
- [ ] [whitespace](https://github.com/ultraware/whitespace)
- [ ] [wsl](https://github.com/bombsimon/wsl)

<details><summary>Linters descriptions for reference</summary>

- [govet](https://golang.org/cmd/vet/) - Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
- [errcheck](https://github.com/kisielk/errcheck) - Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
- [staticcheck](https://staticcheck.io/) - Staticcheck is a go vet on steroids, applying a ton of static analysis checks
- [unused](https://github.com/dominikh/go-tools/tree/master/unused) - Checks Go code for unused constants, variables, functions and types
- [gosimple](https://github.com/dominikh/go-tools/tree/master/simple) - Linter for Go source code that specializes in simplifying a code
- [structcheck](https://github.com/opennota/check) - Finds unused struct fields
- [varcheck](https://github.com/opennota/check) - Finds unused global variables and constants
- [ineffassign](https://github.com/gordonklaus/ineffassign) - Detects when assignments to existing variables are not used
- [deadcode](https://github.com/remyoudompheng/go-misc/tree/master/deadcode) - Finds unused code
- typecheck - Like the front-end of a Go compiler, parses and type-checks Go code
- [bodyclose](https://github.com/timakin/bodyclose) - checks whether HTTP response body is closed successfully
- [golint](https://github.com/golang/lint) - Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
- [rowserrcheck](https://github.com/jingyugao/rowserr) - checks whether Err of rows is checked successfully
- [stylecheck](https://github.com/dominikh/go-tools/tree/master/stylecheck) - Stylecheck is a replacement for golint
- [gosec](https://github.com/securego/gosec) - Inspects source code for security problems
- [interfacer](https://github.com/mvdan/interfacer) - Linter that suggests narrower interface types
- [unconvert](https://github.com/mdempsky/unconvert) - Remove unnecessary type conversions
- [dupl](https://github.com/mibk/dupl) - Tool for code clone detection
- [goconst](https://github.com/jgautheron/goconst) - Finds repeated strings that could be replaced by a constant
- [gocyclo](https://github.com/alecthomas/gocyclo) - Computes and checks the cyclomatic complexity of functions
- [gocognit](https://github.com/uudashr/gocognit) - Computes and checks the cognitive complexity of functions
- [gofmt](https://golang.org/cmd/gofmt/) - Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification
- [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) - Goimports does everything that gofmt does. Additionally it checks unused imports
- [maligned](https://github.com/mdempsky/maligned) - Tool to detect Go structs that would take less memory if their fields were sorted
- [depguard](https://github.com/OpenPeeDeeP/depguard) - Go linter that checks if package imports are in a list of acceptable packages
- [misspell](https://github.com/client9/misspell) - Finds commonly misspelled English words in comments
- [lll](https://github.com/walle/lll) - Reports long lines
- [unparam](https://github.com/mvdan/unparam) - Reports unused function parameters
- [dogsled](https://github.com/alexkohler/dogsled) - Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
- [nakedret](https://github.com/alexkohler/nakedret) - Finds naked returns in functions greater than a specified function length
- [prealloc](https://github.com/alexkohler/prealloc) - Finds slice declarations that could potentially be preallocated
- [scopelint](https://github.com/kyoh86/scopelint) - Scopelint checks for unpinned variables in go programs
- [gocritic](https://github.com/go-critic/go-critic) - The most opinionated Go source code linter
- [gochecknoinits](https://github.com/leighmcculloch/gochecknoinits) - Checks that no init functions are present in Go code
- [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals) - Checks that no globals are present in Go code
- [godox](https://github.com/matoous/godox) - Tool for detection of FIXME, TODO and other comment keywords
- [funlen](https://github.com/ultraware/funlen) - Tool for detection of long functions
- [whitespace](https://github.com/ultraware/whitespace) - Tool for detection of leading and trailing whitespace
- [wsl](https://github.com/bombsimon/wsl) - Whitespace Linter - Forces you to use empty lines!
- [goprintffuncname](https://github.com/jirfag/go-printf-func-name) - Checks that printf-like functions are named with `f` at the end
- [gomnd](https://github.com/tommy-muehle/go-mnd) - An analyzer to detect magic numbers.

</details>

**Comment by Adirio** [comment]
Will provide more info soon

**Comment by Adirio** [comment]
As suggested by @mengqiy in https://github.com/kubernetes-sigs/kubebuilder/pull/1310#discussion_r367616222, we should sort the lints in `verify.sh` so that tracking duplicates is easy.

**Comment by camilamacedo86** [comment]
HI @Adirio, 

I am not sure if we need to use all checks.  regards the missing ones, do you think that all would be really valid to be added or could we close this one?

**Comment by Adirio** [comment]
I don't think we need them all, but this list will keep them tracked to know which ones we have and which we don't.
I think there is no issue with keeping this Issue opened for that reason.

**Comment by camilamacedo86** [comment]
Sorry, I am not sure if I understood. So, what is missing to address here for we are able to close tthis issue?

**Comment by Adirio** [comment]
The question is, do we really need to close this? If we do we can probably create a tag or any other way to group this kind of issues that track changes so that we can search them easily when needed even if they are closed.

**Comment by camilamacedo86** [comment]
The tasks represent the needs/requirements that need to be addressed. So, if it has nothing more that should be done because is obsoleted or referred, for example, then the next step would be close it and describe why. See that any task that has no activity for a while will also be closed by the boot.  

So, why you would like to keep this open? What is missing to be done here?

**Comment by camilamacedo86** [comment]
HI @Adirio, 

the open issues mean needs/tasks that we need to work on. IMO we have in place all lint checks that we need to. So, could you please clarify what in you POV is missing to get done for we close this one?

**Comment by Adirio** [comment]
Technically, we haven't added all linting checks, so we can't say it is really closed. Is it really a problem to leave it open and frozen?

**Comment by camilamacedo86** [comment]
HI @Adirio, 

Has no problem to leave open any task that has actions that should get done. In this case, would we really like to add all possible lint checks? I do not think so. And then, over the lints checks which follow that were not added in the project has anyone here that you think that should be added? 

IMO I do see a reason to add none of the following lint checks and then, in this way, for me, this task should be closed. So, if you would like o keep it open what should be addressed here? What lint still required to be added and why?  

- [ ] [bodyclose](https://github.com/timakin/bodyclose)
- [ ] [depguard](https://github.com/OpenPeeDeeP/depguard)
- [ ] [dogsled](https://github.com/alexkohler/dogsled)
- [ ] [funlen](https://github.com/ultraware/funlen)
- [ ] [gochecknoglobals](https://github.com/leighmcculloch/gochecknoglobals)
- [ ] [gochecknoinits](https://github.com/leighmcculloch/gochecknoinits)
- [ ] [gocognit](https://github.com/uudashr/gocognit)
- [ ] [gocritic](https://github.com/go-critic/go-critic)
- [ ] [godox](https://github.com/matoous/godox)
- [ ] [gomnd](https://github.com/tommy-muehle/go-mnd)
- [ ] [goprintffuncname](https://github.com/jirfag/go-printf-func-name)
- [ ] [rowserrcheck](https://github.com/jingyugao/rowserr)
- [ ] [stylecheck](https://github.com/dominikh/go-tools/tree/master/stylecheck)
- [ ] [whitespace](https://github.com/ultraware/whitespace)
- [ ] [wsl](https://github.com/bombsimon/wsl)

**Comment by Adirio** [comment]
I don't see the need to add them right now but we may want want to add some more in the future. This issue just kept track of which were added and in which PR. But if you want we can close this issue.
