### ISSUE TITLE
[Umbrella] Windows compatibility

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#1405]
# Description

Achieving full compatibility with Windows machines requires several changes that will be tracked in this issue. If any other compatibility fix needs to be provided, in order to achieve Windows compatibility, please comment here and they will be added to the task list

**Task list:**
- [ ] Document `make` dependency for windows: #1406
- [ ] Windows-compatible kubebuilder `Makefile`: #1407
- [ ] Windows-compatible scaffolded `Makefile`: #1408
- [ ] Tests for Windows: #1409

**Comment by Adirio** [comment]
@DirectXMan12 @droot @mengqiy @alexeldeib Did I miss any other point that needs to be tackled to achieve Windows compatibility?

**Comment by DirectXMan12** [comment]
That seems reasonable -- I don't know of any others off the top of my head.  That said, I'm not sure we'll know the full list until it stops exploding :-P

**Comment by estroz** [comment]
Meta: since Windows has a linux subsystem and Unix-like terminal support (cygwin), I wonder:
1. If the combination of these two Windows features makes kubebuilder work without any changes.
1. Even if 1 is true, do many Windows users use Powershell or some other cmd that doesn't work with how kubebuilder is currently configured.

If you have an opinion on this, please comment.

**Comment by camilamacedo86** [comment]
More one : Golden script for Windows #1126. Btw, shows that add as a pre-requirement the usage of  https://www.cygwin.com/  on win could help us to achieve this goal.

**Comment by Adirio** [comment]
@estroz Ideally we shouldn't need to introduce the CygWin development dependency just to port two Makefiles.

**Comment by Adirio** [comment]
This umbrella issue tracks some issues that were detected some time ago about supporting Windows natively. Some of these may be outdated and others may have arisen that aren't detected.

Consensus has been reached in that native windows support would be nice but two things are required:
- Include windows tests in the CI tools, which would require fixing any current issue.
- A maintainer that could help with keeping the windows support once new features are introduced or bugs are detected. If anyone is interested please contact any of the developers here or in the slack channel.

**Comment by camilamacedo86** [comment]
Closed in favor of : https://github.com/kubernetes-sigs/kubebuilder/issues/2940
