### ISSUE TITLE
Plugins Ecosystem Next - Meta issue

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2016]
The propose of this issue is we try to centralize all discussed implementations over the plugin ecosystem for we have a summary definition of all goals and steps that we would like to persuade as their motivations. In this way, we can easily have a better idea and not allow one solution to invalidate another. The details can be found in each task/issue. 

- [x] - Plugin phase 1.5 : PR : https://github.com/kubernetes-sigs/kubebuilder/pull/2060

It will allow us to define more than 1 plugin in the default layout of a project. The layout defines the default/layout plugin(s) config for the project. By doing that, any action/command executed for this configuration would call and use all plugins defined as the default for the project.  

- [x] - Allow every command to overwrite project-configured plugins #1941 : Partial solved in https://github.com/kubernetes-sigs/kubebuilder/pull/2060 but we will still a follow up PR to cover this specific case.  

Allow a user to decide what execution should or not receive the additional plugins scaffolds. By using the `declarative.kubebuilder.io/v1` from above in this scenario users would able to decide what API should or not use the addon pattern instead of applying it for the full project which is the current behaviour before #1991 get merged. 

- [x] - Extract config/base plugin valid for any language/type from Golang: #2015

Allow the community to create any language/type plugin using the same base/config defined by KB in order to ensure its compatibility and/or maintainability. 

- [ ] - Plugin phase 2 https://github.com/kubernetes-sigs/kubebuilder/issues/1378

PS.: Shows that after the above implementations this latest task would be responsible to only check the possibility of the plugins be as separate binaries that can be discovered by the Kubebuilder CLI binary via user-specified plugin file paths

**Comment by Adirio** [comment]
#2019 relates to the second point

**Comment by daniel-garcia** [comment]
Unrelated question: are there any examples of writing a plugin? I can't seem to find anything in the kubebuilder book... maybe I'm not looking in the right place.

**Comment by Adirio** [comment]
> Unrelated question: are there any examples of writing a plugin? I can't seem to find anything in the kubebuilder book... maybe I'm not looking in the right place.

Not really, but planned. This PRs haven't been merged yet so its a bit early. #2060 implements it so you can use the `pkg/plugins` folder as examples.

**Comment by camilamacedo86** [comment]
Hi @daniel-garcia, 

It is not planned here. However, after we get merged #2015 you can for example run `kb it --plugins=config/v1` and get the common base and then, you can indeed scaffold the files with the language that you wish. 

I will

**Comment by camilamacedo86** [comment]
I am closing this one since now we have only  #1378 to be addressed. Then, has no longer need for a meta issue.
