### ISSUE TITLE
[Meta] Stabilize API for v3.0.0

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/kubebuilder#2043]
### Purpose
This Issue will track all the API changes that are considered needed before we can continue with the v3.0.0 release. It only considers breaking changes, adding new exposed APIs can be done in minor/patch releases and therefore do not block the v3.0.0 release.

Being the first release where kubebuilder is considered a library, reviewing the exported API and checking that it is exactly what we want is specially important as v3.X releases will have to offer backwards compatibility related to this API.

### Useful links
- [Latest v3 API](https://pkg.go.dev/sigs.k8s.io/kubebuilder/v3)
- [v3.0.0-beta.0 API](https://pkg.go.dev/sigs.k8s.io/kubebuilder/v3@v3.0.0-beta.0)

### API changes
The list of plugins here are listed in no particular order.
If you find any other change that you consider that should be included, add a comment.

- [x] `pkg/cli`:
    - [x] Remove unexported references in documentation:
    `*cli` is being mentioned in this package's documentation.
        - Issue: #2078
        - Implementation: #2079
    - [x] `WithCompletion` signature:
    Modify the signature in order to reflect that it is an `Option`.
        - Issue: #2044
        - Implementation: #2045

- [x] `pkg/config`
    - [x] `Config` interface:
    Extract the plugin related logic out of the `Config` interface implementations.
        - Issue: #2046
        - Implementation: #2047
    - [x] `Register` signature:
    Remove the unexported `constructorFunc` alias for `func() Config`.
        - Implementation: #2072

- [x] Export internal machinery:
In order to export the internal machinery for the project configuration file and for the project scaffolding, a single filesystem abstraction should be used instead of multiple.
    - Needed for: #2036, #2056
    - [x] Internal utility functions: #2074
    - [x] Single filesystem abstraction: #2080
    - [x] Export scaffolding machinery: #2082
    - [x] Export config persistence machinery: #2083

- [x] Phase 1.5 plugin API:
The API changes in this phase include a different set of subcommand-hooks to enable plugin chaining.
    - [Design document](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1-5.md)
    - [x] Design update: #2075
    - [x] Implementation: #2060

**Comment by camilamacedo86** [comment]
Hi @Adirio, 

I think we are talking here about we address all the next plugin changes described in https://github.com/kubernetes-sigs/kubebuilder/issues/2016 before the plugin 2.0 proposal.

**Comment by Adirio** [comment]
This tracks the ones that are breaking API-wise. If they just add something to the API they can wait for v3.1.0 but if they break the current API they need to be addressed before v3.0.0. This tracks exactly the breaking changes.

**Comment by Adirio** [comment]
All points have been tackled, closing. If any other arises reopen.
