### ISSUE TITLE
Phase 2 Plugins - Meta Issue

### ISSUE THREAD

**Issue by rashmigottipati** [kubernetes-sigs/kubebuilder#2600]
### What do you want to happen?

The propose of this issue is to track Phase 2 Plugins effort and centralize all related discussions here so that the goals and next steps are aligned, and also share with the community on features to expect from Phase 2 Plugins Implementation. 

- [x] [Issue 1378](https://github.com/kubernetes-sigs/kubebuilder/issues/1378)
This is the original feature request created that discusses the main requirements for Phase 2 plugins, which is to have a plugin architecture that supports:
1) Plugins as separate binaries that can be discovered by the Kubebuilder CLI binary.
2) Plugins that are language-agnostic, i.e. they can be written in any language.

- [x] [Phase 2 Design Proposal](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-2.md)
This proposal discusses how to discover and use external plugins, also referred to as out-of-tree plugins (which can be implemented in any language). 

- [x] [Phase 2 Plugins implementation](https://github.com/kubernetes-sigs/kubebuilder/pull/2338)
This PR handles discovery and chaining of external plugins. 

Another goal of this this issue is to track the remaining work that needs to be completed for Phase 2 Plugins:
- [x] documentation; we need to update [Plugin Section](https://book.kubebuilder.io/plugins/plugins.html) on how to create and run an external plugin.

- [x] Provide an example of an external plugin for users. This example could reside under the testdata dir. 

- [x] e2e tests discovering and running the sample plugin.

**Comment by camilamacedo86** [comment]
For we accomplish the goal: 

a) Add samples
We have the PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2810
Also, @rashmigottipati would be great if we could add the python one as well used by you to demo. So we can demonstrate that it can work with any language

b) Add the e2e test to build the binary from the samples added and check that the kubebuilder CLI is capable of to properly using them by creating a project with the external plugin and verifying the result ( very simple we do not need to check all details. )

c) Add the docs and a tutorial to let people know how to create their own plugins that can be consumed by
d) update the plugins doc to let the users know that it is implemented, see: 
- https://book.kubebuilder.io/plugins/plugins.html
- https://book.kubebuilder.io/plugins/creating-plugins.html#future-vision-for-kubebuilder-plugins

Could we update the description of this issue as well accordingly? 

c/c @everettraven

**Comment by camilamacedo86** [comment]
We have now the PR"https://github.com/kubernetes-sigs/kubebuilder/pull/2810
And I think it is very important we move forward with this one

**Comment by HonakerM** [comment]
@rashmigottipati sorry to ping you but do you happen to have an example of a python plugin as mentioned in [this comment?](https://github.com/kubernetes-sigs/kubebuilder/issues/2600#issuecomment-1199073677) No worries if its not ready for a PR I've just been looking into implementing a kubebuilder plugin in python and would love a look at how someone else approached it.

**Comment by rashmigottipati** [comment]
@HonakerM Absolutely. I will create a PR with the example of a python plugin.

**Comment by rashmigottipati** [comment]
@HonakerM https://github.com/rashmigottipati/POC-Phase2-Plugins here's a sample example python plugin. Please let me know if you have any questions or need any help with this!

**Comment by HonakerM** [comment]
@rashmigottipati thank you so much for putting that repo together. It's really helpful in understanding the plugin structure and process. I had one question regarding how kubebuilder discovers these external plugins/executables? Will I have to extended the [kubebuilder executable and bundle my plugin with it?](https://book.kubebuilder.io/plugins/creating-plugins.html#language-based-plugins) Thanks again for your help.

**Comment by Kavinjsir** [comment]
> For we accomplish the goal:
> 
> a) Add samples We have the PR: #2810 Also, @rashmigottipati would be great if we could add the python one as well used by you to demo. So we can demonstrate that it can work with any language
> 
> b) Add the e2e test to build the binary from the samples added and check that the kubebuilder CLI is capable of to properly using them by creating a project with the external plugin and verifying the result ( very simple we do not need to check all details. )
> 
> c) Add the docs and a tutorial to let people know how to create their own plugins that can be consumed by d) update the plugins doc to let the users know that it is implemented, see:
> 
> * https://book.kubebuilder.io/plugins/plugins.html
> * https://book.kubebuilder.io/plugins/creating-plugins.html#future-vision-for-kubebuilder-plugins
> 
> Could we update the description of this issue as well accordingly?
> 
> Also, I am adding it as a priority for the project since we accepted the implementation but we are missing these parts which can make it harder we ensure its maintainability and usability.
> 
> c/c @everettraven

@camilamacedo86 I'm not that much confident that I'd like to join and develop the items you listed.

**Comment by everettraven** [comment]
@Kavinjsir Thanks for taking this on. I am happy to answer any questions you may have and help any way I can. I would take this on myself but I just haven't had the time available to dedicate to writing the e2e tests and documentation :(

**Comment by camilamacedo86** [comment]
All is done. 
During this work extra needs were found and tracked in other issues. 

Great work @Eileen-Yu 🥇
