### ISSUE TITLE
Meta - New deploy-image/v1-alpha plugin follow ups 

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2765]
### What do you want to happen?

Following some tracks, we are able to check and address them as a follow-up of https://github.com/kubernetes-sigs/kubebuilder/pull/2717

- [x] - Add valid status conditions based on the fact that the deployment was successful. ([doc](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)) and [example to update the status in the controller](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L112-L135) - Done in  #2816
- [x] Add markers validations, i.e: 
For the size:

```go
        // The following markers will use OpenAPI v3 schema to validate the value
	// More info: https://book.kubebuilder.io/reference/markers/crd-validation.html
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=3
	// +kubebuilder:validation:ExclusiveMaximum=false

```

Also, would be great if we can add a check for the Port when it is informed. 

- [x] - Improve controller-test to check if the deployment/pod was made 
- [x] - Be able to do checks with images in the e2e and get the PodSatus ( that might mean moving the e2e checks to GitHub action instead of using the prow ) - PR: https://github.com/kubernetes-sigs/kubebuilder/pull/2795
- [x] - For e2e: Ensure that the deployment scaffold on the controller to deploy the Operand is checked 
- [x] - Project file has to track the options used under the plugin and not under the resources. Should we not track under the resources? What happens if we create 2 apis with the plugin? Will we have the image, command and port used for both calls tracked? 
- [x] - [RunAsUser](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go#L146) needs to be a flag arg ( we should not add it by default  )
- [x] - Scaffold controller tests see [here](https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html). We will test if the deployment can be done successfully. (Done : https://github.com/kubernetes-sigs/kubebuilder/pull/2792)
- [x] - Check the project with --namespaced=false flag to create apis. Erro faced when it was used: 
![Screenshot (1118)](https://user-images.githubusercontent.com/7708031/175114565-341ce931-25d9-41ad-85c3-5548e465460c.png): https://github.com/kubernetes-sigs/kubebuilder/pull/2805
- [x ] - Add finializers. ([example](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#external-resources)) - https://github.com/kubernetes-sigs/kubebuilder/pull/2793
- [x ] - change the labels to follow the standards: https://github.com/kubernetes-sigs/kubebuilder/pull/281
- [x ] - Scaffold the image as a new ENV VAR in the config/manager. Todo this one we will need to use the method inserCode ([example](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/deploy-image/v1alpha1/scaffolds/api.go#L144-L153)) and change the controller template to looking for the ENVVAR something like ([example](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#configuring-namespace-scoped-operators)). Done: https://github.com/kubernetes-sigs/kubebuilder/pull/2817

**Comment by camilamacedo86** [comment]
@NikhilSharmaWe I am closing this one since this part you accomplished. Now let's check the community feedback
Great work!

**Comment by camilamacedo86** [comment]
Hi @NikhilSharmaWe 

Back in 2022, you shared a demo video showcasing your contributions to the deploy image plugin, sent via Slack (private message). At that time, you authorised us to share it on the Kubebuilder YouTube channel, documentation, and any other relevant channels or venues—without requiring disclaimers or additional conditions.

Just registering this here for transparency.
I’d appreciate it if you could confirm publicly here as well.

Thanks!

**Comment by NikhilSharmaWe** [comment]
Hi! Yes, I confirm that I had shared the demo video in 2022 and gave permission to share it on the Kubebuilder YouTube channel, documentation, and any other relevant channels, no disclaimers or conditions required. All good to go. Thanks for registering it here!
