### ISSUE TITLE
Meta - Following k8s recommendations about labels

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/kubebuilder#2773]
### What do you want to happen?

It would be nice we ensure that the labels are following the same standards/recommendation defined in: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

What we will need to do?

Assessment:

- [ ] : Check all places that we are scaffolding labels 
- [ ] : Checking our docs and samples to know how we are scaffolding and using labels 
- [ ] : Then, see how we need to change them
- [ ] : Check what could be or not a breaking change for the project/plugins

Proposal 

- [ ] : Propose a solution for what needs to be changed (how)

Perform the changes 
- [ ] - docs/samples
- [ ] - scaffolds / plugin ( maybe we can only change alpha plugins )
