### ISSUE TITLE
Umbrella Issue: Support builder pattern based scaffolding

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#630]
This is an umbrella issue to track implementation of `simplified scaffolding (v2)` as described in https://github.com/kubernetes-sigs/kubebuilder/pull/620

Tasks:

- [x] Add `scaffolding-version` in `init` command
- [x] Read Scaffolding version from `PROJECT` file and use that in `create api` command to scaffold
- [x] Reorganize the scaffold package to support scaffold-version
- [x] Implement simplified scaffolding design proposal
